<a href="https://colab.research.google.com/github/ivn-srg/data-analysis-course-omsu/blob/main/%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B5%201-2/%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B5_1_2_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B_%D0%AF%D0%9F_%D0%B8_%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Основы синтаксиса языка Python


 ## Основные типы данных

### Примитивные типы данных

In [ ]:
# целое число
number = 1_200_000_000_000 # 120000000000

# дробное число
float_number = 12.4

# строки
string = 'Hello world'
another_string = "Hello world"

example_with_quotes = "This string has inner 'quotes'"
format_string = f'This string has integer value {number} and float value {float_number}'

multiline_string = """I can write as many lines here as I want\nAgain and again\t
Again and again
Again and again
Again and again"""

# булево
bool_true = True
bool_false = False

# отсутствие значения
none_var = None

In [ ]:
number, float_number, string, another_string, example_with_quotes, format_string, multiline_string, bool_true, bool_false, none_var

(1200000000000,
 12.4,
 'Hello world',
 'Hello world',
 "This string has inner 'quotes'",
 'This string has integer value 1200000000000 and float value 12.4',
 'I can write as many lines here as I want\nAgain and again\t\nAgain and again\nAgain and again\nAgain and again',
 True,
 False,
 None)

### Коллекции как отдельные типы данных

In [ ]:
# Cписки - простой набор значений любого типа данных
empty_list = []
example_list = [1, 2, 3.5, True, None, [1, 2], (4, 3)]

empty_list, example_list

([], [1, 2, 3.5, True, None, [1, 2], (4, 3)])

In [ ]:
# Множества - набор уникальных значений. Множества гарантируют, что элемент множества будет храниться только в одном экземпляре
empty_set = set()
duplicate_set = set([1, 1, 1, 2, 2, 2, 3, 3, 3])
example_set = set([1, 2, 3.5, True, None])

empty_set, duplicate_set, example_set

(set(), {1, 2, 3}, {1, 2, 3.5, None})

In [ ]:
# Кортежи - неизменяемые списки
empty_tuple = ()
example_tuple = (1, 2, 3.5, True, None, [1, 2], (4, 3))

var = (0, "ФИО")

empty_tuple, example_tuple

((), (1, 2, 3.5, True, None, [1, 2], (4, 3)))

In [ ]:
# Словари - набор пар в виде ключ-значение
empty_dictionary = {}
example_dictionary = {
    0: "zero",
    1: "one",
    2: "two",
    3: "three"
}

empty_dictionary, example_dictionary

'zero'

## Стандартные операции ввода-вывода

In [ ]:
# Консольный ввод
input_string = input()
input_string_with_description = input("Description for your input here: ")

number = int( input() )

12
Description for your input here: 12
12


In [ ]:
# Консольный вывод
print(input_string)
print(input_string_with_description)

print("Input string: " + input_string)
print("Input string:", input_string_with_description)
print(f"Input string: {input_string}, another input string: {input_string_with_description}")

12
12
Input string: 12
Input string: 12
Input string 12, another input string: 12


## Операции с разными типами данных

### Строки

In [ ]:
# Примеры работы со строками

# Создание строки
my_string = "P y t h o n   i s  awesome!"
          #  0 1 2 3 4 5 6 7 8 9

# Длина строки
print(len(my_string))  # Вывод: 18

# Доступ к символам строки
print(my_string[0])  # Вывод: P
print(my_string[-1])  # Вывод: !

# Срезы строки
print( my_string[7:9] )  # Вывод: is
print( my_string[:6] )  # Вывод: Python
print( my_string[10:] )  # Вывод: awesome!

# Методы строк
print(my_string.upper())  # Вывод: PYTHON IS AWESOME!
print(my_string.lower())  # Вывод: python is awesome!
print(my_string.replace("awesome", "great"))  # Вывод: Python is great!

# Форматирование строк
name = "Alice"
age = 25
formatted_string = f"My name is {name} and I am {age} years old."
print(formatted_string)  # Вывод: My name is Alice and I am 25 years old.

### Числа

In [ ]:
# Примеры работы с числами

# Целые числа
int_num = 10
print(int_num)  # Вывод: 10

# Числа с плавающей точкой
float_num = 10.5
print(float_num)  # Вывод: 10.5

# Комплексные числа (это не нужно)
complex_num = 2 + 3j
print(complex_num)  # Вывод: (2+3j)

# Арифметические операции
a = 10
b = 3
print(a + b)  # Сложение: 13
print(a - b)  # Вычитание: 7
print(a * b)  # Умножение: 30
print(a / b)  # Деление: 3.3333...
print(a // b)  # Целочисленное деление: 3
print(a % b)  # Остаток от деления: 1
print(a ** b)  # Возведение в степень: 1000

# Встроенные функции
print(abs(-10))  # Абсолютное значение: 10
print(round(10.567, 1))  # Округление: 10.6
print(max(1, 2, 3))  # Максимум: 3
print(min(1, 2, 3))  # Минимум: 1
print(pow(2, 3)) # Возведение в степень: 8

### Логические операции

In [ ]:
a, b = True, False
print(a and b)  # Логическое И
print(a or b)  # Логическое ИЛИ
print(not a)  # Отрицание

### Коллекции

In [ ]:
# Примеры работы с коллекциями

# Списки
my_list = [1, 2, 3, 4, 5]
my_list.append(6)  # Добавление элемента
print(my_list)  # Вывод: [1, 2, 3, 4, 5, 6]

# Кортежи
my_tuple = (1, 2, 3)
print(my_tuple[0])  # Доступ к элементу: 1

# Множества
my_set = {1, 2, 3}
my_set.add(4)  # Добавление элемента
print(my_set)  # Вывод: {1, 2, 3, 4}

# Словари
my_dict = {'a': 1, 'b': 2}
my_dict['c'] = 3  # Добавление элемента
print(my_dict)  # Вывод: {'a': 1, 'b': 2, 'c': 3}

# Операции с коллекциями
print(len(my_list))  # Длина списка: 6
print(2 in my_list)  # Проверка наличия элемента: True
print(my_list + [7, 8, 9])  # Конкатенация списков: [1, 2, 3, 4, 5, 6, 7, 8, 9]

[1, 2, 3, 4, 5, 6]
1
{1, 2, 3, 4}
{'a': 1, 'b': 2, 'c': 3}
6
True
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
my_list = [1, 2, 3, 4, 5]

mix_num = max(my_list)
min_num = min(my_list)

print("Статистический анализ данных о росте студентов:")
print("-" * 50)
print(f"Минимальный рост: {min_num} см")
# ...

Статистический анализ данных о росте студентов:
--------------------------------------------------
Минимальный рост: 1 см


## 🚦 Условные операторы
Условные операторы — это как охранники на входе в клуб. Они проверяют, соответствуете ли вы определённым условиям, и решают, куда вас направить.

In [ ]:
# Простое условие
age = 19

if age < 18:
    print("Sorry, come back when you're older!")
else:
    print("Welcome to the Python Club! Enjoy your stay!")

Welcome to the Python Club! Enjoy your stay!


In [ ]:
# Примеры операторов сравнения для чисел
x = 10
y = 12.5

# равно
x == y

# не равно
x != y

# х больше у
x > y

# х больше либо равно у
x >= y

# х меньше у
x < y

# х меньше или равно у
x <= y

True

In [ ]:
# Примеры операторов сравнения для строк

string = "str"

# равенство
"str" == string

# неравенство
"str" != string

# вхождение
's' in string
's' not in string

False

In [ ]:
# Условие с elif
z = 7

if z > 10:
  print("z is greater than 10")
elif z > 5:
  print("z is greater than 5 but less than or equal to 10")  # Вывод: z is greater than 5 but less than or equal to 10
elif z == 7:
  print("z is equal 7")
else:
  print("z is less than or equal to 5")

# Вложенные условия
a = 15
if a > 10:
  if a < 20:
      print("a is between 10 and 20")  # Вывод: a is between 10 and 20

z is greater than 5 but less than or equal to 10
a is between 10 and 20


## Циклы

### For

**Цикл — это как очередь за шаурмой**


Представьте, что вы стоите в очереди за шаурмой у ларька. Цикл for — это когда вы по очереди обслуживаете каждого человека перед вами.

**Ситуация:** В очереди 5 человек (список = [Майкл, Миша, Вова, Паша, Галя]).

**Действие:** Продавец делает шаурму для каждого по одному разу (for человек in список:).

**Результат:** Все получают еду, и очередь заканчивается (print("Шаурма готова!")).

In [ ]:
queue = ["Майкл", "Миша", "Вова", "Паша", "Галя"]

for item in queue:
  print(f"Шаурма для человека {item} готова!")


Шаурма для человека Майкл готова!
Шаурма для человека Миша готова!
Шаурма для человека Вова готова!
Шаурма для человека Паша готова!
Шаурма для человека Галя готова!
Галя


In [ ]:
# Примеры циклов

# Цикл for
for i in range(1, 10, 2):
  print(i)  # Вывод: 0 1 2 3 4


# функция range() - функция создания диапазона значений.
# Для простоты понимания будем считать, что range() будет эквивалентом списка, хотя это немного не так.
# например, будем считать, что range(5) вернет список [0, 1, 2, 3, 4]

# Есть три способа вызова range():
#  range(стоп) берет один аргумент
#  range(старт, стоп) берет два аргумента
#  range(старт, стоп, шаг) берет три аргумента

1
3
5
7
9


In [ ]:
# Цикл for с итерацией по списку
my_list = [1, 2, 3, 4, 5]
for item in my_list:
  print(item)  # Вывод: 1 2 3 4 5

In [ ]:
# Цикл while
counter = 0

while counter < 5:
  print(counter)  # Вывод: 0 1 2 3 4
  counter += 1

print("end")

0
1
2
3
4
end


In [ ]:
# Вложенные циклы
for i in range(3):
  for j in range(5):
    print(f"i: {i}, j: {j}")

  print("end second") # Вывод: i: 0, j: 0; i: 0, j: 1; i: 1, j: 0; и т.д.

i: 0, j: 0
i: 0, j: 1
i: 0, j: 2
i: 0, j: 3
i: 0, j: 4
end second
i: 1, j: 0
i: 1, j: 1
i: 1, j: 2
i: 1, j: 3
i: 1, j: 4
end second
i: 2, j: 0
i: 2, j: 1
i: 2, j: 2
i: 2, j: 3
i: 2, j: 4
end second


In [ ]:
matrix = [
    [1, 2, 3],
    [2, 3, 4]
]

In [ ]:
# Использование break и continue
for i in range(10):
  if i == 5:
    break  # Выход из цикла

  if i % 2 == 0:
    continue
  print(i)  # Вывод: 1 3

# for i in range(10):
#   if i % 2 == 0:
#     continue  # Пропуск текущей итерации
#   print(i)

print("df")

1
3
df


In [ ]:
# работа с элементами словаря
school_numbers = {
    "ivanov": [3, 4, 5, 2],
    "petrov": [4, 5, 5, 2],
    "sidorov": [3, 5, 5, 5],
}

for key in school_numbers:
  print(f"ключ: {key}, значение {school_numbers[key]}")

  for value in school_numbers[key]:
    print(value)

ключ: ivanov, значение [3, 4, 5, 2]
3
4
5
2
ключ: petrov, значение [4, 5, 5, 2]
4
5
5
2
ключ: sidorov, значение [3, 5, 5, 5]
3
5
5
5


### Списочные выражения

In [ ]:
# 1. Создание списка с числами
numbers = [x for x in range(10)]
print(numbers)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# 2. Создание списка с условием
even_numbers = [x for x in range(10) if x % 2 == 0]
print(even_numbers)  # [0, 2, 4, 6, 8]

# 3. Изменение элементов списка
squared_numbers = [x**2 for x in range(10)]
print(squared_numbers)  # [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4. Работа со строками
words = ["hello", "world", "python"]
uppercase_words = [word.upper() for word in words]
print(uppercase_words)  # ['HELLO', 'WORLD', 'PYTHON']

# 5. Фильтрация строк
names = ["Alice", "Bob", "Charlie", "David"]
short_names = [name for name in names if len(name) <= 4]
print(short_names)  # ['Bob']

# 6. Применение тернарного оператора
numbers = [x if x % 2 == 0 else "odd" for x in range(10)]
print(numbers)  # [0, 'odd', 2, 'odd', 4, 'odd', 6, 'odd', 8, 'odd']

# 7. Вложенные циклы
pairs = [(x, y) for x in range(3) for y in range(3)]
print(pairs)  # [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

# 8. Работа со словарями
keys = ["name", "age", "city"]
values = ["Alice", 25, "New York"]
dictionary = {k: v for k, v in zip(keys, values)}
print(dictionary)  # {'name': 'Alice', 'age': 25, 'city': 'New York'}

# 9. Генерация множества (set comprehension)
unique_squares = {x**2 for x in [1, 2, 2, 3, 3, 3, 4]}
print(unique_squares)  # {16, 1, 4, 9}

## Функции

> Функции в программировании — это как кулинарные рецепты. Вы пишете инструкции один раз, а затем можете "приготовить" блюдо столько раз, сколько захотите




In [ ]:
def make_pizza(topping1, topping2):
    """This function prepares a delicious pizza with your toppings"""

    print(f"Making a pizza with {topping1} and {topping2}!")
    print("Kneading the dough...")
    print("Adding sauce...")
    print(f"Sprinkling {topping1}...")
    print(f"Adding {topping2}...")
    print("Baking for 15 minutes...")

    return "Your delicious pizza is ready!"

result = make_pizza("pepperoni", "mushrooms")
print(result)

result = make_pizza("pineapple", "ham")
print(result)

Making a pizza with pepperoni and mushrooms!
Kneading the dough...
Adding sauce...
Sprinkling pepperoni...
Adding mushrooms...
Baking for 15 minutes...
Your delicious pizza is ready!
Making a pizza with pineapple and ham!
Kneading the dough...
Adding sauce...
Sprinkling pineapple...
Adding ham...
Baking for 15 minutes...
Your delicious pizza is ready!


In [ ]:
# 2. Глобальная и локальная область видимости
x = 10  # Глобальная переменная

def modify_global():
    global x  # Разрешаем изменять глобальную переменную
    x += 5

modify_global()
print(x)  # 15

In [ ]:
# 3. Локальная область видимости
def local_scope():
    y = 20  # Локальная переменная
    return y

print(local_scope())  # 20
# print(y)  # Ошибка: переменная y не определена вне функции

20


NameError: name 'y' is not defined

In [ ]:
# 4. Передача аргументов: позиционные аргументы
def a(a, b):
    return a + b

print(a(3, 5))  # 8

8


In [ ]:
# 5. Передача аргументов: именованные аргументы
def introduce(name, age):
  return f"My name is {name} and I am {age} years old."

result = introduce(age=25, name="Bob")

print(result)
# My name is Bob and I am 25 years old.

My name is Bob and I am 25 years old.


In [ ]:
# 6. Аргументы по умолчанию
def power(base, exponent=2):
    return base ** exponent

print(power(3))     # 9 (по умолчанию exponent=2)
print(power(3, 3))  # 27

In [ ]:
# 7. Произвольное количество аргументов *args
def sum_all(*args):
    return sum(args)

print(sum_all(1, 2, 3, 4, 5, 6))  # 10

21


In [ ]:
# 8. Произвольное количество именованных аргументов **kwargs
def describe_person(**kwargs):
    return ", ".join(f"{key}: {value}" for key, value in kwargs.items())

print(describe_person(name="Alice", age=30, city="New York"))
# name: Alice, age: 30, city: New York

In [ ]:
# 9. Функции высших порядков: передача функции в аргумент
def apply_twice(func, value):
    return func(func(value))

def square(x):
    return x * x

print(apply_twice(square, 2))  # 16 (2 → 4 → 16)

# 10. Функции высших порядков: возвращение функции
def make_multiplier(n):
    def multiplier(x):
        return x * n
    return multiplier

double = make_multiplier(2)
print(double(5))  # 10

In [ ]:
# 11. Лямбда-функция (анонимная функция)
double_lambda = lambda x: x * 2
print(double_lambda(4))  # 8

# 12. Лямбда в функции высшего порядка (пример с map). Функции высшего порядка - это функции, которые принимаются в качестве аргумента или возвращают другие функции
numbers = [1, 2, 3, 4]
squared_numbers = list(map(lambda x: x ** 2, numbers))
print(squared_numbers)  # [1, 4, 9, 16]

# 13. Лямбда в сортировке
people = [("Alice", 30), ("Bob", 25), ("Charlie", 35)]
sorted_people = sorted(people, key=lambda person: person[1])
print(sorted_people)  # [('Bob', 25), ('Alice', 30), ('Charlie', 35)]

In [ ]:
numbers = '1 2 3 4 5'.split() # ["1", "2", "3"]

for i in range(len(numbers)):
  numbers[i] = int(numbers[i])

numbers

1 2 3 4


[1, 2, 3, 4]

In [ ]:
numbers = [int(item) for item in input().split()]
numbers

1 2 3 4


[1, 2, 3, 4]

In [ ]:
numbers = list(map(int, input().split()))
numbers

1 2 3


[1, 2, 3]

# Библиотеки для получения и обработки данных


In [ ]:
# 1. Работа с модулем math
import math

print(math.sqrt(16))      # 4.0 - квадратный корень
print(math.factorial(5))  # 120 - факториал числа
print(math.pi)            # 3.141592653589793 - значение π
print(math.sin(math.radians(30)))  # 0.5 - синус 30 градусов

In [2]:
# 2. Работа с модулем numpy
import numpy as np

# Создание массива numpy
arr = np.array([1, 2, 3, 4, 5])
print(arr * 2)  # [ 2  4  6  8 10] - умножение массива на число

[ 2  4  6  8 10]


In [3]:
# Создание массива с нулями, единицами и случайными числами
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
random_arr = np.random.rand(3, 3)

print(zeros)
print(ones)
print(random_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.07031528 0.93031487 0.8834135 ]
 [0.327438   0.69502641 0.08896656]
 [0.09957521 0.19242526 0.55866908]]


In [ ]:
# Операции над массивами
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2  # [5 7 9]
double_product = (arr1 + arr2) * 2

print(sum_arr)
print(double_product)

[5 7 9]
[10 14 18]


In [ ]:
# Матрицы и их операции
matrix = np.array([[1, 2], [3, 4]])
transpose = matrix.T  # Транспонирование
inverse = np.linalg.inv(matrix)  # Обратная матрица

print(transpose)
print(inverse)

In [5]:
import numpy as np
import pandas as pd

# Создадим массив NumPy
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Создадим DataFrame Pandas
df = pd.DataFrame(data, columns=['A', 'B', 'C'])

df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [21]:
# 3. Работа с модулем pandas
import pandas

# Создание DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}

df = pandas.DataFrame(data)

df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [22]:
# Доступ к столбцам и строкам
df["Name"]  # Получаем колонку A

df[["Name", "Age"]]  # Получаем только колонки Name и Age

df.iloc[0]  # Первая строка
df.iloc[-1]  # Последняя строка

# Разница между методами в том, что iloc берет строки просто по индексу начиная с начала,
# а loc берет по названию индекса строки
df.loc[0]
df.loc[2]

Name    Charlie
Age          35
City    Chicago
Name: 2, dtype: object

In [23]:
# Фильтрация данных
filtered_df = df[df["Age"] > 28]
filtered_df  # Выведет строки, где возраст больше 28

Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [24]:
# Группировка данных (обязательно нужна какая-то агрегирующая функция)
grouped = df.groupby("City").sum()
grouped

Name  Age
City                     
Chicago      Charlie   35
Los Angeles      Bob   30
New York       Alice   25

In [27]:
# Добавление нового столбца
df["Salary"] = [50000, 60000, 70000]
print(df["Salary"])

# df["D"] = df["A"] + df["B"]  # Создаем новый столбец как сумму двух других

# Удаление столбца
df.drop(columns=["City"], inplace=True)
print(df)

70000
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000


In [ ]:
# сортировка по столбцу
df.sort_values(by=['total', 'py-score'], ascending=[False, False])

In [ ]:
# Работа с пропущенными значениями
df.isnull().sum()  # Подсчитываем количество пропущенных значений

df.fillna(0)  # Заполняем пропуски нулями

df.dropna()  # Удаляем строки с пропущенными значениями

In [ ]:
# описательные характеристики фрейма
df.info()
df.describe()
df.std()

Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0

In [30]:
# Чтение и запись CSV-файлов # Сохранение в CSV
df_read = pd.read_csv("sales_data.csv", skiprows=1)   # Чтение из CSV
df_read
# Основная статистика
# df.describe()
  # Статистика по числовым столбцам (среднее, минимум, максимум и т. д.)
# df.to_csv("sales_data1.csv", index=False)

date product_category   price  quantity  discount  customer_age  \
0    2023-01-01                A  125.99         3         0            29   
1    2023-01-01                B   79.50         2         5            35   
2    2023-01-01                C   49.99         5        10            22   
3    2023-01-01                A  135.75         1         0            41   
4    2023-01-02                B   82.25         3         5            33   
..          ...              ...     ...       ...       ...           ...   
186  2023-03-17                A  127.99         2         0            40   
187  2023-03-18                B   85.99         3         5            32   
188  2023-03-18                C   49.75         6        25            26   
189  2023-03-18                A  136.50         1         0            37   
190  2023-03-19                B   77.75         5        15            35   

     rating  
0         4  
1         5  
2         4  
3         5  
4         3  
..      ...  
186       5  
187       4  
188       4  
189       5  
190       3  

[191 rows x 7 columns]

In [32]:
df_read["price"]

0      125.99
1       79.50
2       49.99
3      135.75
4       82.25
        ...  
186    127.99
187     85.99
188     49.75
189    136.50
190     77.75
Name: price, Length: 191, dtype: float64

In [33]:
df_read = pd.read_csv("ecommerce_customer_data_custom_ratios.csv")
df_read

Customer ID        Purchase Date Product Category  Product Price  \
0             46251  2020-09-08 09:38:32      Electronics             12   
1             46251  2022-03-05 12:56:35             Home            468   
2             46251  2022-05-23 18:18:01             Home            288   
3             46251  2020-11-12 13:13:29         Clothing            196   
4             13593  2020-11-27 17:55:11             Home            449   
...             ...                  ...              ...            ...   
249995        33308  2023-08-10 13:39:06         Clothing            279   
249996        48835  2021-11-23 01:30:42             Home             27   
249997        21019  2020-07-02 14:04:48             Home             17   
249998        49234  2020-12-30 02:02:40            Books            398   
249999        16971  2021-03-13 16:28:35      Electronics            425   

        Quantity  Total Purchase Amount Payment Method  Customer Age  Returns  \
0              3                    740    Credit Card            37      0.0   
1              4                   2739         PayPal            37      0.0   
2              2                   3196         PayPal            37      0.0   
3              1                   3509         PayPal            37      0.0   
4              1                   3452    Credit Card            49      0.0   
...          ...                    ...            ...           ...      ...   
249995         2                   2187         PayPal            55      1.0   
249996         1                   3615    Credit Card            42      1.0   
249997         5                   2466           Cash            41      0.0   
249998         2                   3668         Crypto            34      0.0   
249999         4                   2370           Cash            36      1.0   

              Customer Name  Age  Gender  Churn  
0       Christine Hernandez   37    Male      0  
1       Christine Hernandez   37    Male      0  
2       Christine Hernandez   37    Male      0  
3       Christine Hernandez   37    Male      0  
4               James Grant   49  Female      1  
...                     ...  ...     ...    ...  
249995      Michelle Flores   55    Male      1  
249996          Jeremy Rush   42  Female      1  
249997           Tina Craig   41    Male      0  
249998      Jennifer Cooper   34  Female      1  
249999        Justin Lawson   36  Female      1  

[250000 rows x 13 columns]