<a href="https://colab.research.google.com/github/ivn-srg/data-analysis-course-omsu/blob/main/%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B5%203-4/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B_%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA_Pandas_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Библиотеки для получения и обработки данных


In [ ]:
# 1. Работа с модулем math
import math

print(math.sqrt(16))      # 4.0 - квадратный корень
print(math.factorial(5))  # 120 - факториал числа
print(math.pi)            # 3.141592653589793 - значение π
print(math.sin(math.radians(30)))  # 0.5 - синус 30 градусов

In [ ]:
# 2. Работа с модулем numpy
import numpy as np

# Создание массива numpy
arr = np.array([1, 2, 3, 4, 5])
print(arr * 2)  # [ 2  4  6  8 10] - умножение массива на число

[ 2  4  6  8 10]


In [ ]:
# Создание массива с нулями, единицами и случайными числами
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
random_arr = np.random.rand(3, 3)

print(zeros)
print(ones)
print(random_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.07031528 0.93031487 0.8834135 ]
 [0.327438   0.69502641 0.08896656]
 [0.09957521 0.19242526 0.55866908]]


In [ ]:
# Операции над массивами
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2  # [5 7 9]
double_product = (arr1 + arr2) * 2

print(sum_arr)
print(double_product)

[5 7 9]
[10 14 18]


In [ ]:
# Матрицы и их операции
matrix = np.array([[1, 2], [3, 4]])
transpose = matrix.T  # Транспонирование
inverse = np.linalg.inv(matrix)  # Обратная матрица

print(transpose)
print(inverse)

In [ ]:
import numpy as np
import pandas as pd

# Создадим массив NumPy
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Создадим DataFrame Pandas
df = pd.DataFrame(data, columns=['A', 'B', 'C'])

df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
# 3. Работа с модулем pandas
import pandas

# Создание DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}

df = pandas.DataFrame(data)

df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
# Доступ к столбцам и строкам
df["Name"]  # Получаем колонку A

df[["Name", "Age"]]  # Получаем только колонки Name и Age

df.iloc[0]  # Первая строка
df.iloc[-1]  # Последняя строка

# Разница между методами в том, что iloc берет строки просто по индексу начиная с начала,
# а loc берет по названию индекса строки
df.loc[0]
df.loc[2]

Name    Charlie
Age          35
City    Chicago
Name: 2, dtype: object

In [ ]:
# Фильтрация данных
filtered_df = df[df["Age"] > 28]
filtered_df  # Выведет строки, где возраст больше 28

Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
# Группировка данных (обязательно нужна какая-то агрегирующая функция)
grouped = df.groupby("City").sum()
grouped

Name  Age
City                     
Chicago      Charlie   35
Los Angeles      Bob   30
New York       Alice   25

In [ ]:
# Добавление нового столбца
df["Salary"] = [50000, 60000, 70000]
print(df["Salary"])

# df["D"] = df["A"] + df["B"]  # Создаем новый столбец как сумму двух других

# Удаление столбца
df.drop(columns=["City"], inplace=True)
print(df)

70000
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000


In [ ]:
# сортировка по столбцу
df.sort_values(by=['total', 'py-score'], ascending=[False, False])

In [ ]:
# Работа с пропущенными значениями
df.isnull().sum()  # Подсчитываем количество пропущенных значений

df.fillna(0)  # Заполняем пропуски нулями

df.dropna()  # Удаляем строки с пропущенными значениями

In [ ]:
# описательные характеристики фрейма
df.info()
df.describe()
df.std()

Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0

In [ ]:
# Чтение и запись CSV-файлов # Сохранение в CSV
df_read = pd.read_csv("sales_data.csv", skiprows=1)   # Чтение из CSV
df_read

# Основная статистика
# df.describe()
  # Статистика по числовым столбцам (среднее, минимум, максимум и т. д.)
# df.to_csv("sales_data1.csv", index=False)

date product_category   price  quantity  discount  customer_age  \
0    2023-01-01                A  125.99         3         0            29   
1    2023-01-01                B   79.50         2         5            35   
2    2023-01-01                C   49.99         5        10            22   
3    2023-01-01                A  135.75         1         0            41   
4    2023-01-02                B   82.25         3         5            33   
..          ...              ...     ...       ...       ...           ...   
186  2023-03-17                A  127.99         2         0            40   
187  2023-03-18                B   85.99         3         5            32   
188  2023-03-18                C   49.75         6        25            26   
189  2023-03-18                A  136.50         1         0            37   
190  2023-03-19                B   77.75         5        15            35   

     rating  
0         4  
1         5  
2         4  
3         5  
4         3  
..      ...  
186       5  
187       4  
188       4  
189       5  
190       3  

[191 rows x 7 columns]

In [ ]:
df_read["price"]

0      125.99
1       79.50
2       49.99
3      135.75
4       82.25
        ...  
186    127.99
187     85.99
188     49.75
189    136.50
190     77.75
Name: price, Length: 191, dtype: float64

In [ ]:
df_read = pd.read_csv("ecommerce_customer_data_custom_ratios.csv")
df_read

Customer ID        Purchase Date Product Category  Product Price  \
0             46251  2020-09-08 09:38:32      Electronics             12   
1             46251  2022-03-05 12:56:35             Home            468   
2             46251  2022-05-23 18:18:01             Home            288   
3             46251  2020-11-12 13:13:29         Clothing            196   
4             13593  2020-11-27 17:55:11             Home            449   
...             ...                  ...              ...            ...   
249995        33308  2023-08-10 13:39:06         Clothing            279   
249996        48835  2021-11-23 01:30:42             Home             27   
249997        21019  2020-07-02 14:04:48             Home             17   
249998        49234  2020-12-30 02:02:40            Books            398   
249999        16971  2021-03-13 16:28:35      Electronics            425   

        Quantity  Total Purchase Amount Payment Method  Customer Age  Returns  \
0              3                    740    Credit Card            37      0.0   
1              4                   2739         PayPal            37      0.0   
2              2                   3196         PayPal            37      0.0   
3              1                   3509         PayPal            37      0.0   
4              1                   3452    Credit Card            49      0.0   
...          ...                    ...            ...           ...      ...   
249995         2                   2187         PayPal            55      1.0   
249996         1                   3615    Credit Card            42      1.0   
249997         5                   2466           Cash            41      0.0   
249998         2                   3668         Crypto            34      0.0   
249999         4                   2370           Cash            36      1.0   

              Customer Name  Age  Gender  Churn  
0       Christine Hernandez   37    Male      0  
1       Christine Hernandez   37    Male      0  
2       Christine Hernandez   37    Male      0  
3       Christine Hernandez   37    Male      0  
4               James Grant   49  Female      1  
...                     ...  ...     ...    ...  
249995      Michelle Flores   55    Male      1  
249996          Jeremy Rush   42  Female      1  
249997           Tina Craig   41    Male      0  
249998      Jennifer Cooper   34  Female      1  
249999        Justin Lawson   36  Female      1  

[250000 rows x 13 columns]

In [ ]:
import pandas as pd
import numpy as np
data = {
    'Товар': ['Хлеб', 'Молоко', 'Кофе', 'Чай', 'Сахар'],
    'Цена': [100, 150, 300, 200, 50],
    'Продажи': [2000, 1500, 500, 1200, 600]
}
df = pd.DataFrame(data)
mean_price = df['Цена'].mean()
mean_sales = df['Продажи'].mean()
highest_price_product = df.loc[df['Цена'].idxmax(), 'Товар']
highest_sales_product = df.loc[df['Продажи'].idxmax(), 'Товар']
print(f'Среднее значение для Цена: {mean_price}')
print(f'Среднее значение для Продажи: {mean_sales}')
print(f'Товар с самой высокой ценой: {highest_price_product}')
print(f'Товар с самыми высокими продажами: {highest_sales_product}')

Среднее значение для Цена: 160.0
Среднее значение для Продажи: 1160.0
Товар с самой высокой ценой: Кофе
Товар с самыми высокими продажами: Хлеб


pandas.core.series.Series